micronaut:
  application:
    name: projetoPix

grpc:
  server:
    port: ${SERVER_PORT:50051}
    keep-alive-time: 1h
    max-inbound-message-size: 1024

datasources:
  default:
    url: jdbc:postgresql://localhost:5432/postgres
    driverClassName: org.postgresql.Driver
    username: postgres
    password: 1234
    schema-generate: CREATE_DROP
    dialect: POSTGRES

jpa.default.properties.hibernate.hbm2ddl.auto: update
jpa.default.properties.hibernate.show_sql: update
jpa.default.properties.hibernate.format_sql: update

itau:
  url: http://localhost:9091/api/v1

bcb:
  url: http://localhost:8082/api/v1/pix